
/*dummydata to use*/

INSERT INTO Users (userName, email, password) VALUES 
('John Doe', 'john.doe@example.com', 'password1'),
('Jane Smith', 'jane.smith@example.com', 'password2'),
('Michael Brown', 'michael.brown@example.com', 'password3'),
('Emily Davis', 'emily.davis@example.com', 'password4'),
('William Johnson', 'william.johnson@example.com', 'password5'),
('Olivia Wilson', 'olivia.wilson@example.com', 'password6'),
('James Taylor', 'james.taylor@example.com', 'password7'),
('Sophia Martinez', 'sophia.martinez@example.com', 'password8'),
('Benjamin Lee', 'benjamin.lee@example.com', 'password9'),
('Isabella Anderson', 'isabella.anderson@example.com', 'password10'),
('Liam White', 'liam.white@example.com', 'password11'),
('Ava Thompson', 'ava.thompson@example.com', 'password12'),
('Henry Harris', 'henry.harris@example.com', 'password13'),
('Mia Clark', 'mia.clark@example.com', 'password14'),
('Lucas Lewis', 'lucas.lewis@example.com', 'password15'),
('Charlotte Robinson', 'charlotte.robinson@example.com', 'password16'),
('Elijah Walker', 'elijah.walker@example.com', 'password17'),
('Amelia Scott', 'amelia.scott@example.com', 'password18'),
('Noah Young', 'noah.young@example.com', 'password19'),
('Harper King', 'harper.king@example.com', 'password20');

INSERT INTO Questions (Question, category, QuestionDate, `Like`, userId) VALUES 
('What is the capital of France?', 'Geography', NOW(), 0, 1),
('What is the largest ocean on Earth?', 'Geography', NOW(), 0, 2),
('Who wrote "Pride and Prejudice"?', 'Literature', NOW(), 0, 3),
('What is the square root of 64?', 'Mathematics', NOW(), 0, 4),
('Who discovered penicillin?', 'Science', NOW(), 0, 5),
('What is the tallest mountain in the world?', 'Geography', NOW(), 0, 6),
('When was the first manned moon landing?', 'History', NOW(), 0, 7),
('What is the fastest land animal?', 'Biology', NOW(), 0, 8),
('Which element has the chemical symbol O?', 'Chemistry', NOW(), 0, 9),
('What is the smallest country in the world?', 'Geography', NOW(), 0, 10),
('Who painted the Mona Lisa?', 'Art', NOW(), 0, 11),
('What is the speed of light?', 'Physics', NOW(), 0, 12),
('What is the longest river in the world?', 'Geography', NOW(), 0, 13),
('Who invented the telephone?', 'History', NOW(), 0, 14),
('What is the hardest natural substance?', 'Science', NOW(), 0, 15),
('What is the most abundant gas in Earth’s atmosphere?', 'Science', NOW(), 0, 16),
('What planet is known as the Red Planet?', 'Astronomy', NOW(), 0, 17),
('How many continents are there?', 'Geography', NOW(), 0, 18),
('Who was the first president of the United States?', 'History', NOW(), 0, 19),
('Which planet is closest to the sun?', 'Astronomy', NOW(), 0, 20);


INSERT INTO Answers (Answer, AnswersDate, userId, questionId) VALUES 
('Paris', NOW(), 1, 1), 
('Pacific Ocean', NOW(), 2, 2), 
('Jane Austen', NOW(), 3, 3), 
('Eight', NOW(), 4, 4), 
('Alexander Fleming', NOW(), 5, 5), 
('Mount Everest', NOW(), 6, 6), 
('1969', NOW(), 7, 7), 
('Cheetah', NOW(), 8, 8), 
('Oxygen', NOW(), 9, 9), 
('Vatican City', NOW(), 10, 10), 
('Leonardo da Vinci', NOW(), 11, 11), 
('299,792,458 m/s', NOW(), 12, 12), 
('Nile River', NOW(), 13, 13), 
('Alexander Graham Bell', NOW(), 14, 14), 
('Diamond', NOW(), 15, 15), 
('Nitrogen', NOW(), 16, 16), 
('Mars', NOW(), 17, 17), 
('Seven', NOW(), 18, 18), 
('George Washington', NOW(), 19, 19), 
('Mercury', NOW(), 20, 20);